/**
 * ============================================================
 * 📁 File: config/rombuzzGifts.js
 * 🎁 Purpose: Server-side source of truth for RomBuzz gift validation,
 * pricing, Cloudinary image URLs, and placement rules.
 *
 * Used by:
 *  - routes/gifts.js
 *  - routes/buzzpost/buzz.post.gifts.js
 *  - routes/buzzpost/buzz.media.gifts.js
 *
 * Important:
 *  - Never trust frontend gift price.
 *  - Frontend sends only giftId.
 *  - Backend validates giftId, placement, priceBC, and enabled state.
 *  - Gift names are internal only and should not be shown in the app UI.
 * ============================================================
 */

const ALL_PLACEMENTS = [
  "reels",
  "posts",
  "profile_media",
  "chat",
  "buzzpoke",
  "microbuzz",
  "match_celebration",
  "streak",
  "universal",
];

const ROMBUZZ_GIFT_CONFIG = [
  {
    giftId: "pink_heart",
    name: "Pink Heart",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097131/pink_heart_u0byvz.png",
    priceBC: 5,
    category: "romantic",
    rarity: "common",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "heart_red",
    name: "Red Heart",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097124/heart_red_wpi6mn.png",
    priceBC: 8,
    category: "romantic",
    rarity: "common",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "heart_s",
    name: "Heart Spark",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596844/heart_s_vmawu7.png",
    priceBC: 9,
    category: "romantic",
    rarity: "common",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "tea_cup",
    name: "Tea Cup",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097135/tea_cup_tddkrl.png",
    priceBC: 10,
    category: "sweet",
    rarity: "common",
    animation: "softFloat",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "three_buns",
    name: "Three Buns",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097136/three_buns_secb0a.png",
    priceBC: 12,
    category: "sweet",
    rarity: "common",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "cherry_love",
    name: "Cherry Love",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097120/cherry_love_l7q10k.png",
    priceBC: 15,
    category: "playful",
    rarity: "common",
    animation: "cherryBounce",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "love_ribbon",
    name: "Love Ribbon",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097130/love_ribbon_auytjx.png",
    priceBC: 18,
    category: "romantic",
    rarity: "common",
    animation: "ribbonWave",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "autumn_love",
    name: "Autumn Love",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097119/autumn_love_cx8v8h.png",
    priceBC: 20,
    category: "seasonal",
    rarity: "common",
    animation: "autumnDrift",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "red_rose",
    name: "Red Rose",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097132/red_rose_uhu0nz.png",
    priceBC: 25,
    category: "romantic",
    rarity: "common",
    animation: "roseBloom",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "sparkling_rose",
    name: "Sparkling Rose",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097133/sparkling_rose_hj6imz.png",
    priceBC: 30,
    category: "romantic",
    rarity: "common",
    animation: "sparkleRise",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "cuddle_love",
    name: "Cuddle Love",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097122/cuddle_love_d0h9yv.png",
    priceBC: 35,
    category: "sweet",
    rarity: "uncommon",
    animation: "zoomPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "cute_birds",
    name: "Cute Birds",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097122/cute_birds_av7c4u.png",
    priceBC: 40,
    category: "romantic",
    rarity: "uncommon",
    animation: "birdsFlutter",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "love_birds",
    name: "Love Birds",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097127/love_birds_n3dy21.png",
    priceBC: 45,
    category: "romantic",
    rarity: "uncommon",
    animation: "birdsFlutter",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "love_candle",
    name: "Love Candle",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097127/love_candle_mdhh0y.png",
    priceBC: 50,
    category: "romantic",
    rarity: "uncommon",
    animation: "candleFlicker",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "candle_light",
    name: "Candle Light",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097119/candle_light_mzncuw.png",
    priceBC: 55,
    category: "romantic",
    rarity: "uncommon",
    animation: "lanternGlow",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "love_lantern",
    name: "Love Lantern",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097130/love_lantern_hdqnio.png",
    priceBC: 60,
    category: "romantic",
    rarity: "uncommon",
    animation: "lanternGlow",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "lantern_blue",
    name: "Blue Lantern",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097125/lantern_blue_jv8vhy.png",
    priceBC: 65,
    category: "romantic",
    rarity: "uncommon",
    animation: "glowPulse",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "love_capsule",
    name: "Love Capsule",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097128/love_capsule_ta0dbc.png",
    priceBC: 70,
    category: "romantic",
    rarity: "rare",
    animation: "capsuleDrop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "lock_key",
    name: "Lock Key",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097126/lock_key_hyqsfj.png",
    priceBC: 75,
    category: "romantic",
    rarity: "rare",
    animation: "lockShake",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "flower_vase",
    name: "Flower Vase",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097124/flower_vase_pxkt3h.png",
    priceBC: 80,
    category: "romantic",
    rarity: "rare",
    animation: "sway",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "bonsai_love",
    name: "Bonsai Love",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097120/bonsai_love_hf11ft.png",
    priceBC: 90,
    category: "premium",
    rarity: "rare",
    animation: "bonsaiBreath",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "rombuzz_love",
    name: "RomBuzz Love",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097133/rombuzz_love_mjkaak.png",
    priceBC: 100,
    category: "premium",
    rarity: "rare",
    animation: "glowPulse",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "cake_slice",
    name: "Cake Slice",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576293/cake_slice_zunipf.png",
    priceBC: 100,
    category: "sweet",
    rarity: "rare",
    animation: "softFloat",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "velvet_kiss",
    name: "Velvet Kiss",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097137/velvet_kiss_taofc4.png",
    priceBC: 120,
    category: "premium",
    rarity: "epic",
    animation: "kissBurst",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "pink_rose_premium",
    name: "Pink Rose",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575934/pink_rose_vng77w.png",
    priceBC: 120,
    category: "romantic",
    rarity: "rare",
    animation: "roseBloom",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "star_teddy",
    name: "Star Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/star_teddy_ppbbo8.png",
    priceBC: 140,
    category: "sweet",
    rarity: "rare",
    animation: "twinkle",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "love_compass",
    name: "Love Compass",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097129/love_compass_iinnhg.png",
    priceBC: 150,
    category: "premium",
    rarity: "epic",
    animation: "compassSpin",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "diamond_ring_classic",
    name: "Diamond Ring Classic",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575916/diamond_ring__z4udhx.png",
    priceBC: 160,
    category: "premium",
    rarity: "rare",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "star_compass",
    name: "Star Compass",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596850/Star_Compass_a1rilv.png",
    priceBC: 180,
    category: "premium",
    rarity: "epic",
    animation: "twinkle",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "red_balloon",
    name: "Red Balloon",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575891/red_balloon_k0qdlx.png",
    priceBC: 180,
    category: "playful",
    rarity: "rare",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "crown_heart",
    name: "Crown Heart",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596845/crown_heart_exnbyn.png",
    priceBC: 190,
    category: "premium",
    rarity: "rare",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "green_teddy",
    name: "Green Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/green_teddy_qavcx0.png",
    priceBC: 200,
    category: "sweet",
    rarity: "rare",
    animation: "softFloat",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "magic_heart",
    name: "Magic Heart",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/magic_heart_xoaaib.png",
    priceBC: 220,
    category: "romantic",
    rarity: "rare",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "flowers_bouquet",
    name: "Flowers Bouquet",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/flowers_sqyobi.png",
    priceBC: 240,
    category: "romantic",
    rarity: "rare",
    animation: "sparkleRise",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "crystal_swan",
    name: "Crystal Swan",
    imageUrl: "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097121/crystal_swan_gzjhyu.png",
    priceBC: 250,
    category: "premium",
    rarity: "legendary",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "blue_teddy",
    name: "Blue Teddy",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596831/Blue_bears_lhldsv.png",
    priceBC: 260,
    category: "sweet",
    rarity: "rare",
    animation: "sway",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "small_bird",
    name: "Small Bird",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/small_bird_a0uzlo.png",
    priceBC: 280,
    category: "playful",
    rarity: "rare",
    animation: "birdsFlutter",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "vanilla_cake",
    name: "Vanilla Cake",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/vanilla_cake_ia68pd.png",
    priceBC: 300,
    category: "sweet",
    rarity: "epic",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "bright_moon",
    name: "Bright Moon",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/bright_moon_pdtns4.png",
    priceBC: 320,
    category: "premium",
    rarity: "epic",
    animation: "glowPulse",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "work_teddy",
    name: "Work Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/work_teddy_fkyics.png",
    priceBC: 340,
    category: "funny",
    rarity: "epic",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "scarf",
    name: "Cozy Scarf",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/scarf_pqwq01.png",
    priceBC: 360,
    category: "sweet",
    rarity: "epic",
    animation: "ribbonWave",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "cute_monkey",
    name: "Cute Monkey",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575891/cute_monkey_ygfnem.png",
    priceBC: 380,
    category: "funny",
    rarity: "epic",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "very_big_cake",
    name: "Very Big Cake",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/very_big_cake_xqm6lz.png",
    priceBC: 400,
    category: "celebration",
    rarity: "epic",
    animation: "zoomPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "diamond_ring_luxe",
    name: "Diamond Ring Luxe",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/diamond__ring_xj5dgl.png",
    priceBC: 420,
    category: "premium",
    rarity: "epic",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "key_heart",
    name: "Key Heart",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596849/Key_heart_pkfse5.png",
    priceBC: 440,
    category: "romantic",
    rarity: "epic",
    animation: "lockShake",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "compass_moon",
    name: "Compass Moon",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596838/compass_moon_mktxvn.png",
    priceBC: 460,
    category: "premium",
    rarity: "epic",
    animation: "compassSpin",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "big_diamond",
    name: "Big Diamond",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575891/big_diamond_u6ep7e.png",
    priceBC: 480,
    category: "premium",
    rarity: "epic",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "real_moon",
    name: "Real Moon",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576292/real_moon_pu131m.png",
    priceBC: 500,
    category: "premium",
    rarity: "epic",
    animation: "glowPulse",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "red_teddy",
    name: "Red Teddy",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596830/red_teddy_cevl4w.png",
    priceBC: 520,
    category: "sweet",
    rarity: "epic",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "crystal_rose",
    name: "Crystal Rose",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596834/Crystal_Rose_hjyjqd.png",
    priceBC: 540,
    category: "premium",
    rarity: "legendary",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "gold_paper_plane",
    name: "Gold Paper Plane",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596829/pink_Paper_Plane_with_gold_vwv0n1.png",
    priceBC: 560,
    category: "premium",
    rarity: "legendary",
    animation: "softFloat",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "velvet_cup",
    name: "Velvet Cup",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596837/sexy_cup_ju3vhb.png",
    priceBC: 580,
    category: "premium",
    rarity: "legendary",
    animation: "candleFlicker",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "winged_lips",
    name: "Winged Lips",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596847/wings_lips_bbhxcu.png",
    priceBC: 600,
    category: "romantic",
    rarity: "legendary",
    animation: "kissBurst",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "balloon_golden_lips",
    name: "Golden Lips Balloon",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596843/balloon_golden_lips_jz7kbv.png",
    priceBC: 610,
    category: "romantic",
    rarity: "legendary",
    animation: "kissBurst",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "kiss_pop",
    name: "Kiss Pop",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596848/kiss_m6xnyk.png",
    priceBC: 620,
    category: "romantic",
    rarity: "legendary",
    animation: "kissBurst",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "magic_love",
    name: "Magic Love",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596836/magic_love_xlzjv1.png",
    priceBC: 640,
    category: "romantic",
    rarity: "legendary",
    animation: "sparkleRise",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "white_heart_balloon",
    name: "White Heart Balloon",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596841/balloon_heart_white_layonp.png",
    priceBC: 660,
    category: "celebration",
    rarity: "legendary",
    animation: "softFloat",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "magic_cup",
    name: "Magic Cup",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596832/magic_cup_xajxhn.png",
    priceBC: 680,
    category: "premium",
    rarity: "legendary",
    animation: "glowPulse",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "crystal_gold_music_note",
    name: "Crystal Gold Music Note",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596833/Crystal_Gold_Music_Note_ljdxev.png",
    priceBC: 700,
    category: "premium",
    rarity: "legendary",
    animation: "twinkle",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "golden_filigree_key",
    name: "Golden Filigree Key",
    imageUrl: 
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596839/Golden_Filigree_Key_u5guag.png",
    priceBC: 720,
    category: "premium",
    rarity: "legendary",
    animation: "lockShake",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "big_cake",
    name: "Big Cake",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/big_cake_qygctx.png",
    priceBC: 740,
    category: "celebration",
    rarity: "legendary",
    animation: "zoomPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "crystal_perfume_bottle",
    name: "Crystal Perfume Bottle",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596846/Crystal_Perfume_Botle_j424og.png",
    priceBC: 740,
    category: "premium",
    rarity: "legendary",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "happy_cow",
    name: "Happy Cow",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/happy_cow_j9gjof.png",
    priceBC: 760,
    category: "funny",
    rarity: "legendary",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "red_heart_premium",
    name: "Premium Red Heart",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575953/red_heart_rwtaoz.png",
    priceBC: 780,
    category: "romantic",
    rarity: "legendary",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "happy_teddy",
    name: "Happy Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576233/happy_teddy_amniiy.png",
    priceBC: 800,
    category: "sweet",
    rarity: "legendary",
    animation: "bounceIn",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "red_lips",
    name: "Red Lips",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/red_lips_onusi5.png",
    priceBC: 820,
    category: "romantic",
    rarity: "legendary",
    animation: "kissBurst",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "diamond_ring_spark",
    name: "Diamond Ring Spark",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/diamond_ring_ftc468.jpg",
    priceBC: 840,
    category: "premium",
    rarity: "ultra",
    animation: "crystalShine",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "hug_teddy",
    name: "Hug Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/hug_teddy_umuydb.png",
    priceBC: 860,
    category: "sweet",
    rarity: "ultra",
    animation: "heartPop",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "cute_teddy",
    name: "Cute Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/cute_teddy_mmvfny.png",
    priceBC: 880,
    category: "sweet",
    rarity: "ultra",
    animation: "sway",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "sing_teddy",
    name: "Sing Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/sing_teddy_sscobz.png",
    priceBC: 900,
    category: "playful",
    rarity: "ultra",
    animation: "twinkle",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "rain_teddy",
    name: "Rain Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/rain_teddy_m2kfma.png",
    priceBC: 930,
    category: "sweet",
    rarity: "ultra",
    animation: "softFloat",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "plant_teddy",
    name: "Plant Teddy",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/plant_teddy_jk85jr.png",
    priceBC: 960,
    category: "sweet",
    rarity: "ultra",
    animation: "bonsaiBreath",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    giftId: "happy_bear",
    name: "Happy Bear",
    imageUrl: "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/happy_bear_xkmpyp.png",
    priceBC: 1000,
    category: "exclusive",
    rarity: "ultra",
    animation: "glowPulse",
    animated: true,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  }
];

const GIFT_MAP = new Map(
  ROMBUZZ_GIFT_CONFIG.map((gift) => [String(gift.giftId), gift])
);

function getGiftConfig(giftId) {
  return GIFT_MAP.get(String(giftId || "")) || null;
}

function isGiftEnabled(giftId) {
  const gift = getGiftConfig(giftId);
  return Boolean(gift && gift.enabled);
}

function getGiftPriceBC(giftId) {
  const gift = getGiftConfig(giftId);
  return gift ? Number(gift.priceBC) : null;
}

function canUseGiftInPlacement(giftId, placement) {
  const gift = getGiftConfig(giftId);
  const place = String(placement || "universal");

  return Boolean(
    gift &&
      gift.enabled &&
      Array.isArray(gift.allowedPlacements) &&
      gift.allowedPlacements.includes(place)
  );
}

function validateGiftPurchase({ giftId, placement }) {
  const gift = getGiftConfig(giftId);
  const place = String(placement || "universal");

  if (!gift) {
    return {
      ok: false,
      code: "INVALID_GIFT",
      message: "Gift does not exist.",
    };
  }

  if (!gift.enabled) {
    return {
      ok: false,
      code: "GIFT_DISABLED",
      message: "Gift is not currently available.",
    };
  }

  if (
    !Array.isArray(gift.allowedPlacements) ||
    !gift.allowedPlacements.includes(place)
  ) {
    return {
      ok: false,
      code: "INVALID_PLACEMENT",
      message: "Gift cannot be used in this placement.",
    };
  }

  return {
    ok: true,
    gift,
    priceBC: Number(gift.priceBC) || 0,
  };
}

module.exports = {
  ROMBUZZ_GIFT_CONFIG,
  getGiftConfig,
  isGiftEnabled,
  getGiftPriceBC,
  canUseGiftInPlacement,
  validateGiftPurchase,
};