const mongoose = require("mongoose");

const pushTokenSchema = new mongoose.Schema(
  {
    token: { type: String, required: true },
    platform: { type: String, default: "" },
    deviceId: { type: String, default: "" },
    appOwnership: { type: String, default: "" },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
    lastSeenAt: { type: Date, default: Date.now },
  },
  {
    _id: false,
  }
);

const userSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    email: { type: String, required: true, unique: true, index: true },
    firstName: { type: String, default: "" },
    lastName: { type: String, default: "" },
    passwordHash: { type: String, default: "" },
    googleId: { type: String, default: "" },
    gender: { type: String, default: "" },
    genderVisibility: { type: String, default: "public" },
    pronouns: { type: String, default: "" },
    orientation: { type: String, default: "" },
    orientationVisibility: { type: String, default: "public" },
    dob: { type: String, default: "" },
    city: { type: String, default: "" },
    country: { type: String, default: "" },
    hometown: { type: String, default: "" },
    latitude: { type: Number, default: null },
    longitude: { type: Number, default: null },
    location: { type: Object, default: null },
    distanceVisibility: { type: String, default: "public" },
    travelMode: { type: Boolean, default: false },
    bio: { type: String, default: "" },
    voiceUrl: { type: String, default: "" },
    vibeTags: { type: [String], default: [] },
    lookingFor: { type: String, default: "" },
    relationshipStyle: { type: String, default: "" },
    interestedIn: { type: [String], default: [] },
    height: { type: String, default: "" },
    bodyType: { type: String, default: "" },
    fitnessLevel: { type: String, default: "" },
    smoking: { type: String, default: "" },
    drinking: { type: String, default: "" },
    workoutFrequency: { type: String, default: "" },
    diet: { type: String, default: "" },
    sleepSchedule: { type: String, default: "" },
    educationLevel: { type: String, default: "" },
    school: { type: String, default: "" },
    jobTitle: { type: String, default: "" },
    company: { type: String, default: "" },
    languages: { type: [String], default: [] },
    religion: { type: String, default: "" },
    politicalViews: { type: String, default: "" },
    zodiac: { type: String, default: "" },
    interests: { type: [String], default: [] },
    hobbies: { type: [String], default: [] },
    favoriteMusic: { type: [String], default: [] },
    favoriteMovies: { type: [String], default: [] },
    travelStyle: { type: String, default: "" },
    petsPreference: { type: String, default: "" },
    likes: { type: String, default: "" },
    dislikes: { type: String, default: "" },
    favorites: { type: [String], default: [] },
    avatar: { type: String, default: "" },
    photos: { type: [String], default: [] },
    media: { type: [Object], default: [] },
    visibilityMode: { type: String, default: "full" },
    fieldVisibility: { type: Object, default: {} },
    visibility: { type: String, default: "active" },
    preferences: { type: Object, default: {} },
    settings: { type: Object, default: {} },
    pushTokens: { type: [pushTokenSchema], default: [] },
    matchPref: { type: Object, default: {} },
    locationRadius: { type: Number, default: 50 },
    ageRange: { type: Object, default: { min: 18, max: 99 } },
    profileComplete: { type: Boolean, default: false },
    hasOnboarded: { type: Boolean, default: false },
    lastActive: { type: Date, default: Date.now },
    profileViews: {
      total: { type: Number, default: 0 },
      today: { type: Number, default: 0 },
      lastViewDate: { type: String, default: "" },
    },
    premiumTier: { type: String, default: "free" },
    isPremium: { type: Boolean, default: false },
    isVerified: { type: Boolean, default: false },
    blockedUsers: { type: [String], default: [] },
    verificationCode: { type: String, default: "" },
    codeExpiresAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    minimize: true,
  }
);

module.exports =
  mongoose.models.User || mongoose.model("User", userSchema);
